### PR TITLE
Added championmastery, moved API URLs to their respective methods

### PR DESCRIPTION
**Pull request by naoey**
This way I think it will be easier to add any future additions to the API even if their structure changes like it did with championmastery.

All the tests in tests.py passed.

I don't think my usage of a dict to map regions to platforms is the cleanest way, but atm I wasn't able to work in a better solution. I'll take any suggestions you may have :)

### CODE REVIEW

**Comment by fab0l1n** [comment]
ok, tested it and works as expected, except the region argument is optional atm, which may return an KeyError in line 337, so this should be checked first. Then the method will look like this:

>         def _champion_mastery_request(self, url, region, **kwargs):
>             if region is None:
>                 region = self.default_region
>             return self.base_request(
>                 'championmastery/location/{platform}/player/{url}'.format(
>                     platform=platforms[region],
>                     url=url
>                 ),
>                 region,
>                 **kwargs
>             )

**Comment by naoey** [comment]
Right, I misread the platforms dict as `{"NORTH_AMERICA":"NA1"}`. I'll fix that up.

**Comment by naoey** [comment]
The lowercasing was for correct behaviour in case the method was called with a string like `'NA'` instead of the constant `riotwatcher.NORTH_AMERICA`. The remaining methods still work in this scenario using the capital NA in the request URL. But for championmastery it will throw a KeyError while getting the platform. I'm not sure if this is meant to be handled, but it does keep the behaviour consistent.

**Comment by naoey** [comment]
Closing as this is no longer relevant with the new API updates.

**Pull request closed without merging**
