### PR TITLE
Address issue #84

### PR DESCRIPTION
**Pull request by darrendlin**
Remove leagues/by-summoner endpoint as it no longer exists

### CODE REVIEW

**Comment by pseudonym117** [comment]
I merged your other changes, so I think you may need to get those changes to assess the merge conflicts  

The other issue that was part of #84 was that the examples in the documentation are using the old endpoint, so those need to be updated as well

**Comment by darrendlin** [comment]
Okay I'll get to them later today.

**Comment by pseudonym117** [comment]
Awesome, thanks for the help with these issues

**Comment by darrendlin** [comment]
Not really sure what I can do to make codecov to stop complaining...

**Comment by pseudonym117** [comment]
Its likely because you removed code that was tested, which means the overall coverage has gone down. No issue here though.

I will try to test these latest today to double check there wont be any issues, then should be able to merge and upload new version to pypi

**Comment by darrendlin** [comment]
Sounds great

**Comment by pseudonym117** [comment]
looks good, there are a few random things in the documentation that still need to be addressed, but i will fix those now...

**Pull request merged**
