### PR TITLE
Travis support.

### PR DESCRIPTION
**Pull request by cdvv7788**
Added basic support for travis using unittest.
For this to work, you will need to setup a travis account for your repository and add an enviroment variable named RIOT_API_KEY with your api key. I commented out all your tests but one to lay out the basis for this change. I will start refactoring them a little.

You can add a travis badge: http://docs.travis-ci.com/user/status-images/

### CODE REVIEW

**Comment by cdvv7788** [comment]
I changed the tests to follow unittest structure. Most of the tests are independent, only saving summoner globally to avoid making a lot of unnecessary requests to the API.
The tests are pretty basic, checking only if the response is not None. They may require further work.

**Comment by cdvv7788** [comment]
To run this on travis, you will need to limit the concurrent builds to 1 to avoid w.can_make_requests() returning erroneous messages.

**Comment by cdvv7788** [comment]
@pseudonym117 Is there something else required for you to accept this?

**Comment by pseudonym117** [comment]
sorry, I haven't had time to go through and learn exactly what Travis does. Don't want to merge something I don't understand, so assuming everything is good with your pull request, I'll merge it when I learn Travis. I'll try to do this soon

**Comment by cdvv7788** [comment]
Travis is just a continuos integration service. It is free for open source projects. All it does is run your tests once you push something to your repository.
I changed the tests a little and currently they are only checking that the response is not None, so there may be space for improvement. However i think that is a good start, as we can check if every change to the code does not break anything automatically (both python 2.7 and 3.4).
Other than merging, you will need to create an account and the webhook for travis to work. You will also need to set a couple things, like putting the api_key in an enviroment variable and limiting tests to 1 thread to avoid breaking rate limit (all travis settings).
I added a little useful links in https://github.com/pseudonym117/Riot-Watcher/issues/32

**Comment by pseudonym117** [comment]
suuuuuuuuper late, but i managed to get this actually set up. not through this though, and without environment variables.

**Pull request closed without merging**
