### PR TITLE
Introduce async to Riot-Watcher "Hello World!"

### PR DESCRIPTION
**Pull request by SirGhostal**
# Intro
My fork aims to **convert riotwatcher to async** and enable it to make HTTP requests to the RiotGames API without blocking the main event loop. This is very important when using the riotwatcher library in an async application.. Running all requests with [asyncio.run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) is no fun at all.

**PLEASE NOTE:** This PR is **not** complete & development will need to continue on it.

Also: before merging; a few key decisions should be made such as whether this PR should have its own branch inside riotwatcher.

# TODO
- [ ] Maintain Python2 compatibility. Back to good old @asyncio.coroutine syntax.
- [ ] Ensure the handlers are called and executed safely in an async enviornment

# Example of use
The following example demonstrates the potential of what async can do.
```py
from riotwatcher import Riotwatcher
import asyncio

api_key = "RGAPI-XXXX"

loop = asyncio.get_event_loop()

riotwatcher = Riotwatcher(api_key, loop=loop)


async def champion_rotations(region):
    return await riotwatcher.champion.rotations(region)


async def get_summoner(region, name):
    return await riotwatcher.summoner.by_name(region, name)


if __name__ == "__main__":
    region = "euw1"
    username = "SirGhostal"

    # Get the free to play champions in a given region.
    free_champions = loop.run_until_complete(champion_rotations(region))
    print(free_champions)

    # Load up summoner account information by region and username.
    summoner = loop.run_until_complete(get_summoner(region, username))
    print(summoner)
```

# Additional Notes
Please by all means; criticise this PR and feel free to contribute to ensure the final implementation is flawless.
Many thanks,
Zach

### CODE REVIEW

**Comment by pseudonym117** [comment]
This pull request **introduces 31 alerts** when merging 3bdd77113ab7e7b7147ed96db3339a2834ec81be into a728158e114e51ffa9b13a24307a0992499225ee - [view on LGTM.com](https://lgtm.com/projects/g/pseudonym117/Riot-Watcher/rev/pr-9ec1e2dc3eef28cc42fe6206906f0d39da3e4124)

**new alerts:**

* 19 for Syntax error
* 11 for Property in old\-style class
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by pseudonym117** [comment]
This pull request **introduces 20 alerts** when merging d7a513127b7853ba01cd32c59709ee273a27ae78 into a728158e114e51ffa9b13a24307a0992499225ee - [view on LGTM.com](https://lgtm.com/projects/g/pseudonym117/Riot-Watcher/rev/pr-6227c51478d60f57a3ce6babf8327f732f26b585)

**new alerts:**

* 19 for Syntax error
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by pseudonym117** [comment]
This pull request **introduces 19 alerts** when merging df366510cef9d21c80abf6ded710d86b7b16e3d6 into a728158e114e51ffa9b13a24307a0992499225ee - [view on LGTM.com](https://lgtm.com/projects/g/pseudonym117/Riot-Watcher/rev/pr-3bdd4b4cdb64992119a640e9880d349c4985750f)

**new alerts:**

* 19 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by pseudonym117** [comment]
automatic code reports are angry, but this is not a huge issue atm. I am changing the branch which this is going to be merged to. After at least CI checks pass, I'll merge these changes to that branch.

Code analysis / coverage isnt important at the moment, just that tests pass.

These are the core concerns I have in what will finally be merged to master (whether you take care of it or I do, doesnt matter):

- no breaking API changes - async should be opt-in, not required be default
- python 2.7 still functions as a synchronous wrapper
  - it is completely acceptable if async definitions are hidden behind `if sys.version_info >= (3,5):`
- as much logic as possible should be shared between async and synchronous code paths (mostly, rate limiter)

**Comment by SirGhostal** [comment]
Perhaps passing `async=True` as a kwarg into riotwatcher would be a good idea. However we can have a line during __init__ saying
```py
self.async = True if async and sys.version_info >= 3.5 else False
```

I'll take a look into sharing async and sync code in the rate limit handler. The main two issues here are having to define both async and synchronous versions of a function... and also we need a differen't type of lock in the rate limit handler as a threading.Lock wouldn't work. Maybe having a line saying:
```py
self._lock = asyncio.Lock() if self._async else threading.Lock()
```
However we then run into issues because we need to use `async with` instead of a simple `with` statement when using this lock.. Unsure how this could be achieved and we may need to have seperate folders inside the handlers directory for each respective one rate limiter.

**Comment by pseudonym117** [comment]
I think `async=True` is a good idea, though if its passed in an unsupported python version, I would just throw an exception and error out right away. 

I think 90% of the Rate Limiter code is synchronous and doesnt do any long operations. The only parts which I think need to be changed is the lock and the sleep. I think it'd be fine if we could contain the lock and sleep into one class, and have both an async and synchronous implementation. Then every other class could run with the assumption that they have a lock and be shared.

**Pull request merged**
